### ISSUE TITLE
Android 4.4+ Camera.getPicture External Storage error

### ISSUE THREAD

**Issue by doomboy00** [AppGyver/steroids#787] opened 2015-01-27 14:35 UTC
Having just tested my app on a few devices I found that on those using an external storage device (SD card) I get a capture error returning staing ‘Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=15376, uid=10297 required android.permission.READEXTERNALSTORAGE or grantUriPermission()' is the build service missing this permission? Is there something we can add to the app.coffee for this permission?

**Comment by doomboy00** [comment] 2015-01-27 16:26
After some playing around I found the issue is to do with the manifest permission:

<uses-permission
     android:name="android.permission.WRITE_EXTERNAL_STORAGE"
     android:maxSdkVersion="18" />

Which is correctly set up in steroids as instructed here: http://developer.android.com/guide/topics/manifest/uses-permission-element.html

But upon some testing doesn't seem to be the case, so decompiling and recompiling with the permission without the maximum SDK:

<uses-permission
     android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

Did the trick for me. Is there any downside to this? If not can this be changed back in the steroids builds?

(Trail of me talking to myself here: https://forums.appgyver.com/#!/steroids-build-service:android-cameragetpicture-e)

**Comment by pre** [comment] 2015-01-28 09:01
There's no downside, the error you got previously was that `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` is already defined and build resulted in an error having two different definitions for this attribute. 

After you removed `maxSdkVersions` the two definitions became identical, hence, the build error went away. The Crosswalk Manifest looks like this: https://gist.github.com/pre/c29860151a904a1b2c4b

I'm pretty sure we have it documented somewhere, but the search on our docs really sucks and even I cannot find it. (That should be fixed, but it's an other issue.)

**Comment by doomboy00** [comment] 2015-01-28 09:46
Okay so is this something that I can fix then? (Without having to build, then decompile and recompile outside of steroids?) Or is it something with the build service?

**Comment by pre** [comment] 2015-01-28 13:03
Is there an error if you remove `android.permission.WRITE_EXTERNAL_STORAGE` from your plugin altogether? Defining it in the plugin is not supposed to have any effect because this permission is already requested in the top-level AndroidManifest.xml.

**Comment by doomboy00** [comment] 2015-01-28 13:30
I'm getting confused here, what plugin? I'm not knowingly re-defining this anywhere, i believe the problem to be a cause of the top-level AndroidManifest.xml having the ```maxSdkVersions``` within the ```android.permission.WRITE_EXTERNAL_STORAGE``` definition which isn't working as it should (as defined by developer.android.com).

**Comment by manujbahl** [comment] 2015-01-28 21:09
Can anyone help figure out how to decompile the apk. I did an adhoc build from appgyver and used http://www.decompileandroid.com to decompile the generated apk. 
However I don't see the AndroidManifest.xml in the generated source. Any idea on using a different service to decompile.

**Comment by mikkol26** [comment] 2015-01-29 07:01
"Is there an error if you remove android.permission.WRITE_EXTERNAL_STORAGE from your plugin altogether? " The fact is that at the moment you're not able to use the camera with builds from AppGyver cloud service. If I've understood correctly these workarounds, the issue is that "android:maxSdkVersion="18" is defined for WRITE_EXTERNAL_STORAGE at the moment by default plugins which breaks the camera functionality.

**Comment by pre** [comment] 2015-01-29 08:39
@manujbahl You can view the signed `AndroidManifest.xml` using `apktool`, see http://stackoverflow.com/a/3231037/422848

@mikkol26 Camera plugin is already included by default, and there is already `android.permission.WRITE_EXTERNAL_STORAGE` defined in the main `AndroidManifest.xml`. The original error in this issue was caused by a duplicate (conflicting) definition of this same permission, therefore removing the conflicting permission (defined by the plugin) helped.

@doomboy00 top-level `AndroidManifest.xml` does not have `maxSdkVersion` defined at all.

Could you please elaborate on what is the problem? There's a working camera example in the old Kitchensink project: https://github.com/AppGyver/kitchensink -- if you scan that, does your camera work? It should.

**Comment by pre** [comment] 2015-01-29 08:49
There's new information in the forums about this issue, claiming that the default Camera no longer works since 4.0.4 (== 4.0.4-edge6).

I'll need to investigate this. It's possibly caused because of the updated File plugin.

**Comment by mikkol26** [comment] 2015-01-29 09:50
Somehow the latest updates to plugins are causing this. You can reproduce this issue as follows:
- Build https://github.com/AppGyver/kitchensink in AppGyver cloud --> Camera works
- Build https://github.com/AppGyver/kitchensink in AppGyver cloud with this plugin {"source":"https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git"} --> Camera doesn't work but gives the access error mentioned above.

**Comment by pre** [comment] 2015-01-29 09:52
There are now two different issues here:

1) Updated File plugin seems to cause issues with the Camera plugin in 4.0.5-edge2. This will be investigated.

2) Custom plugin, which defines a duplicate (conflicting) value for a permission. The conflicting value is this: https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/blob/master/plugin.xml#L59 

The conflicting permission must be removed from the plugin, it is already defined in the top-level `AndroidManifest.xml`.

**Comment by mikkol26** [comment] 2015-01-29 09:59
Isn't it possible to merge the values in build process, so that 
<config-file target="AndroidManifest.xml" parent="/manifest">
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="18"/>
    </config-file>

<config-file target="AndroidManifest.xml" parent="/manifest">
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE">
    </config-file>

would become 

<config-file target="AndroidManifest.xml" parent="/manifest">
      <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE">
    </config-file>

This way it wouldn't require a fork of every plugin that defines the permission with "android:maxSdkVersion". Furthermore, was it not defined previously in the top-level AndroidManifest.xml because I didn't see this issue like two weeks ago?

**Comment by pre** [comment] 2015-01-29 10:15
The permission has always been defined in the top-level manifest, but it started conflicting only after the plugin tried to define it differently (multiple identical definitions are not an issue).

However, either forking all the third-party plugins to your account or locking them to a specifig "good-version" would be a good idea anyway. If you blindly build your application using the bleeding-edge plugin code from the plugin repo's master branch, you will end up with problems when the third-party plugin suddenly changes without you knowing it.

**Comment by pre** [comment] 2015-01-29 12:43
I checked Camera and File related tests and couldn't find any other issue with 4.0.5-edge2 and Camera. I'm closing this as an error with a third-party plugin. Please open a new one if you encounter an issue which wasn't mentioned here.

**Closed by pre** 2015-01-29 12:43 UTC
