### ISSUE TITLE
iOS and Android custom URL issues.

### ISSUE THREAD

**Issue by manujbahl** [AppGyver/steroids#862] opened 2015-03-10 23:14 UTC
We are having some issues with custom url implementation for both iOS and Android.

iOS.
On iOS custom url works fine when the app is in background. But if the app needs to be fired up it presents an error dialog on the splash screen.

Android
On Android the app gets and stays hung at the splash screen when launched/opened up through a custom url.

Could you please take a look at these and if there is an available fix or a known workaround, I would be interested in knowing about that.
As previously noted, we are currently blocked from shipping ur app pending resolution to these issues .

Thanks
Manuj.

![619c3891-9990-4029-8972-b8cfa14232924373f692-7500-458f-a2a9-3e2f23293a46](https://cloud.githubusercontent.com/assets/5688107/6587359/7d749526-c740-11e4-8634-a0a636afa201.jpg)
![screenshot_2015-03-10-16-00-05](https://cloud.githubusercontent.com/assets/5688107/6587360/7d9284dc-c740-11e4-9236-2d516db2f8bf.png)

**Comment by harsaharsa** [comment] 2015-03-11 15:52
See https://github.com/AppGyver/steroids/issues/861 for an update to the Android issue – iOS is still under investigation!

**Comment by harsaharsa** [comment] 2015-03-13 09:29
https://github.com/AppGyver/steroids/issues/868 is probably the cause of the iOS error, can you verify? I'm closing this issue now, please comment if your issue is not fixed by #868.

**Closed by harsaharsa** 2015-03-13 09:29 UTC
Labels: investigating

**Comment by manujbahl** [comment] 2015-03-13 17:52
Hey Harri,

I verified and yes you are right that the url is available in the ready notification.
However I still see the error alert coming up on the splash screen before the main view is shown.

That is still an issue.

Can you see if there is a fix for that ?

Manuj

**Comment by manujbahl** [comment] 2015-03-13 17:56
I can only verify a part fix. The url is available in the ready notification. However i still see the error alert on the splash screen.

**Comment by manujbahl** [comment] 2015-03-16 17:56
Harry can you reopen the issue.
on iOS i do see that we get the url on device ready. but we can seem to get rid of the error alert that comes up on the splash screen. The alert does not seem to some from any of our code and is probably from some initialization code that we can't seem to get a handle on.

**Comment by harsaharsa** [comment] 2015-03-17 12:00
Can you search for `onerror` in your project? Steroids project used to have a `www/javascripts/onerror.js` that had the following code, which would produce the exact alert you see.

```
(function(previousOnError) {

window.onerror = function(errorMsg, url, lineNumber) {
  var formattedMsg = url+":"+lineNumber+" "+errorMsg;
  console.log(formattedMsg);
  alert(formattedMsg);

  if (previousOnError) {
    previousOnError(errorMsg, url, lineNumber);
  };
};

})(window.onerror);
```

**Comment by manujbahl** [comment] 2015-03-17 18:01
Thanks Harri

That was it .. Commenting out that alert prevent it from coming up.
But, is that the right thing to do ? What else gets affected by taking the alert out? Will it prevent other legitimate instances of the alert from showing when it really needs to be shown ? Also any idea of what the actual underlying problem is and how that can be fixed ?

Thanks
Manuj.

**Comment by harsaharsa** [comment] 2015-03-19 15:43
The alert is just saying that you have SOME error in your app (the `onerror` event listener is triggered) that happens when it opens, caused by e.g. a wrong function call, something being undefined or whatever else. It doesn't have to do with custom URI schemes – you just have a JavaScript error in your app you need to hunt down. :)

You can try opening your app's WebViews Safari debugger and running CMD+R to refresh the page, which should give you access to any errors that happen during page load.
