### ISSUE TITLE
AppGyver support for Windows 8.1 and Windows Phone apps

### ISSUE THREAD

**Issue by Scuttman** [AppGyver/steroids#797] opened 2015-01-29 19:26 UTC
It would be great to be able to package steroids apps for Windows 8.1 or Windows Phone. The potential for developing apps for this platform is huge and I would love to be able to do this using Steroids rather than recoding my apps for Windows via Visual Studio.

Please consider this for your roadmap!

**Comment by pre** [comment] 2015-02-02 08:59
This is a duplicate of https://github.com/AppGyver/steroids/issues/707 

Follow-up there.

**Closed by pre** 2015-02-02 08:59 UTC
