### ISSUE TITLE
Unknown Provider Issue - Angular Module Injection

### ISSUE THREAD

**Issue by justincolangelo** [AppGyver/steroids#892] opened 2015-03-31 17:25 UTC
I'd like to use `ngSanitize` in my project. 

    angular
        .module('home', ['ngSanitize'])
        .controller('IndexController', function($scope, supersonic) {
        });

It is installed as a bower component. The script tag is added to include it in the layout. It appears after the `angular.js` reference and right before the `supersonic.js` reference. I verified that it is including in the page using the safari debugger.

This error happens when I try to use `angular-sanitize.js` in my project. 

    Error: [$injector:unpr] Unknown provider: supersonicProvider <- supersonic <- LoginController
    http://errors.angularjs.org/1.3.15/$injector/unpr?p0=supersonicProvider%20%3C-   %20supersonic%20%3C-%20LoginController
    http://localhost/components/angular/angular.js:63:32
    http://localhost/components/angular/angular.js:4015:34
    getService@http://localhost/components/angular/angular.js:4162:46
    http://localhost/components/angular/angular.js:4020:48
    getService@http://localhost/components/angular/angular.js:4162:46
    invoke@http://localhost/components/angular/angular.js:4194:23
    http://localhost/components/angular/angular.js:8493:27
    http://localhost/components/angular/angular.js:7739:23
    forEach@http://localhost/components/angular/angular.js:331:24
    nodeLinkFn@http://localhost/components/angular/angular.js:7738:18
    compositeLinkFn@http://localhost/components/angular/angular.js:7117:23
    compositeLinkFn@http://localhost/components/angular/angular.js:7120:24
    publicLinkFn@http://localhost/components/angular/angular.js:6996:45
    http://localhost/components/angular/angular.js:1457:27
    $eval@http://localhost/components/angular/angular.js:14466:28
    $apply@http://localhost/components/angular/angular.js:14565:28 
    bootstrapApply@http://localhost/components/angular/angular.js:1455:21
    invoke@http://localhost/components/angular/angular.js:4203:22
    doBootstrap@http://localhost/components/angular/angular.js:1453:20
    bootstrap@http://localhost/components/angular/angular.js:1473:23
    angularInit@http://localhost/components/angular/angular.js:1367:14
    http://localhost/components/angular/angular.js:26304:16
    trigger@http://localhost/components/angular/angular.js:2762:9
    eventHandler@http://localhost/components/angular/angular.js:3032:25

**Comment by harsaharsa** [comment] 2015-04-01 12:34
Can you get everything to load correctly in a web browser? Sounds like just an Angular setup issue. While `steroids connect` is running, you can access the files via `http://localhost:4567/` that serves the contents of `dist/` directly. Ie. if your view is  e.g. `dist/home/views/index.html`, you can view it in a web browser via `http://localhost:4567/home/views/index.html`, which will help debugging.

**Comment by mydearxym** [comment] 2015-05-17 06:46
same issue , i am not even inject ngAnimate ....

```javascript 
angular.module.("example", ["ngAnimate"])

```

**Comment by justincolangelo** [comment] 2015-05-17 12:43
Did you run `bower install ngAnimate` and verify that you have the script included in your `layout` file? Check out the `/dist` folder and make sure the script exists.

    <script src="/components/angular/angular.js"></script>
    <script src="/components/ngAnimate/js/angular-animate.min.js"></script>

And in the controller:

    angular
        .module('example', ['ngAnimate'])
        .controller('LearnMoreController', function($scope, supersonic) {
            // do things here
        });

**Comment by harsaharsa** [comment] 2015-05-19 09:46
See https://github.com/AppGyver/steroids/issues/941 – closing this since it's not a bug/feature request per se, and more of a "How do I use AngularJS" type question. Please continue the discussion on https://forums.appgyver.com (that said, the answer above should help you in the right direction!).

**Closed by harsaharsa** 2015-05-19 09:46 UTC
