### ISSUE TITLE
getLaunchURL uses AG_STEROIDS_SCANNER_URL not AG_APP_STARTUP_URL

### ISSUE THREAD

**Issue by roberto-robles** [AppGyver/steroids#764] opened 2015-01-16 17:59 UTC

**Comment by pre** [comment] 2015-01-19 07:53
iOS or Android?

Does it affect only Scanner?

**Comment by roberto-robles** [comment] 2015-01-20 00:54
Sorry for the missing info, this was present on Android 4.0.3 build version. Now testing on 4.0.4-edge5 I am checking that both vars window.AG_APP_STARTUP_URL and window.AG_STEROIDS_SCANER_URL have set the same URL, but int the getLaunch definition is using the AG_STEROIDS_SCANNER_URL. So it works but don't know if this could carry problems on the future.

Here is the getLaunchURL definition that I am seeing right now:

   steroids.app.getLaunchURL
   function (options, callbacks) {
       if (options == null) {
         options = {};
       }
       if (callbacks == null) {
         callbacks = {};
       }
       return window.AG_STEROIDS_SCANNER_URL;
     }

**Comment by roberto-robles** [comment] 2015-01-20 00:56
One more thing I'm doing AdHoc builds for now.

**Comment by pre** [comment] 2015-01-20 07:37
Thanks for reporting!

That's true, `steroids.app.getLaunchURL()` is supposed to give out the url used for launching the application via a custom url scheme. It sounds weird that it refers to `window.AG_STEROIDS_SCANNER_URL`.

If you create a custom build and define a custom protocol (url scheme) for it, and then use that to launch your application (eg. my-app://something), what do you see in 1) getLaunchURL, 2) AG_APP_STARTUP_URL ?

**Comment by roberto-robles** [comment] 2015-01-20 17:09
Update with 4.0.4-edge5 Android build steroids.app.getLaunchURL() works fine!

**Comment by roberto-robles** [comment] 2015-02-06 01:01
Bug remains, even on Adhoc If I check for AG_APP_STARTUP_URL and I launched the app using a custom-url the only value that is being set is AG_STEROIDS_SCANNER_URL

**Comment by pre** [comment] 2015-02-06 12:19
K, thx, I'll take a look soon.

**Comment by harsaharsa** [comment] 2015-02-26 14:48
`AG_STEROIDS_SCANNER_URL` is the correct one to use, even though it is badly named. It will store the full custom scheme URL that is used to launch the app.

`AG_APP_STARTUP_URL` is legacy, it was used on iOS to force-reload Prototyper applications. When it was implemented into Android, its purpose was misinterpreted and thus its intended usage was miscommunicated. We will be removing it from Android soon to avoid further confusion.

Another thing is to handle the bad and confusing naming...

Since steroids.app.getLaunchURL() functions as intended, I'm closing this issue!

**Closed by harsaharsa** 2015-02-26 14:48 UTC
Labels: bug, Steroids.js
