### ISSUE TITLE
Disable keyboard shrink view on Android

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#792] opened 2015-01-28 11:48 UTC
Right now, when keyboard is opened on Android (in non fullscreen mode, that is, with status bar visible) the view is being stretched causing weird behavior and it looks ugly. This should be fixed to allow disable the shrinkView

**Comment by pre** [comment] 2015-02-02 09:02
Streching appears in the Crosswalk runtime but not in the platform WebView.

This is caused by the Crosswalk internals. This [bug is discussed in the Crosswalk Jira](https://crosswalk-project.org/jira/browse/XWALK-2012?focusedCommentId=25025&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25025).

It's nothing we can do about now, but we are in continuous discussion with the Crosswalk team about the most burning Crosswalk issues we're having. Thanks for the heads up. :)

**Comment by pre** [comment] 2015-02-02 09:03
The stretch issue is here: https://github.com/AppGyver/steroids/issues/574 -- I'll close this ticket as a duplicate.

**Closed by pre** 2015-02-02 09:03 UTC
