### ISSUE TITLE
Error at install steroids (Node 5 and NPM 3)

### ISSUE THREAD

**Issue by horochovec** [AppGyver/steroids#1078] opened 2015-11-17 16:01 UTC
Environment 

horochovec: mediaglobe$ node --version
v5.0.0
horochovec: mediaglobe$ npm --version
3.3.6

npm WARN EPEERINVALID generator-steroids@1.0.20 requires a peer of yo@>=1.0.0 but none was installed.

**Comment by Leeds-eBooks** [comment] 2015-11-17 16:06
npm 3 deprecates peer dependencies, could this be because of that?

**Comment by harsaharsa** [comment] 2015-11-19 09:54
Yup, npm 3 doesn't work with Steroids CLI currently. Closing this as duplicate of https://github.com/AppGyver/steroids/issues/1055

**Closed by harsaharsa** 2015-11-19 09:54 UTC

**Comment by mansoor-spark** [comment] 2015-11-24 00:29
Hi Harsa -
I downgraded my npm version 3 to npm version 2 but I still get the below error when installing Steroids:

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✖ npm version

Your npm version is outdated.

Upgrade to the latest version by running:
npm install -g npm

Found potential issues on your machine :(
/usr/local/bin/steroids -> /usr/local/lib/node_modules/steroids/bin/steroids
