### ISSUE TITLE
Unexpected battery drain on standalone builds on Android

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#841] opened 2015-02-24 10:59 UTC
Users have reported battery drain on standalone Supersonic apps.

**Comment by pre** [comment] 2015-02-24 11:35
This is a different issue than https://github.com/AppGyver/steroids/issues/761

**Comment by PeanutButterCo** [comment] 2015-03-03 13:04
+1

**Comment by nikalabs** [comment] 2015-03-03 18:17
+1

**Comment by atif-kht** [comment] 2015-03-03 18:18
+10001

**Comment by DerekMarcinyshyn** [comment] 2015-03-03 18:20
+1

**Comment by buzzware** [comment] 2015-03-05 09:45
This will be a deal breaker for me if not fixed. I don't see why Supersonic/Steroids should use any more CPU than plain Cordova

**Comment by pre** [comment] 2015-03-05 11:47
If you know how to reproduce this issue, ie what kind of combinations cause unexpected  battery drain, please report it here. It is not consistent and not all applications seem to be affected.

**Comment by cryoutsolutions** [comment] 2015-03-28 10:54
I also wrote on issue #583 

Hi,

I also want to report a case:
I have tested this issue on 3 phones and on all I have the same issue.

First I believed that the issue is from my app but with the default hello world app it acts the same way. The issue being that the cpu is over 20% both with app running and in the background.

I tried with google play version of scanner and also with a custom build. The same issue. The standalone version has the same issue.

Devices:
HTC M7 Android 5.0.2
MI 3 Android 4.4
Samsung S4 4.4.2

Appgyver is v4.0.4
Steroids is v4.0.13
I used Crosswalk
Maybe is something from how my computer builds the app? I have OSX 10.10.1

Thanks

**Comment by harsaharsa** [comment] 2015-03-30 14:29
So to reiterate, all Supersonic apps consume 20% cpu regardless of their content? Does it only happen after WebViews are loaded, i.e. not in the initial scan screen?

**Comment by cryoutsolutions** [comment] 2015-03-30 16:08
It's only happening after the webviews are loaded.

**Comment by EdwinRikkers** [comment] 2015-04-02 15:09
+1

**Comment by EdwinRikkers** [comment] 2015-04-07 14:40
What is the estimate off this issue when this will be fixed? We are having some customers that have issues with this. Do you need more info on this issue ?

**Comment by emc2spider** [comment] 2015-04-08 09:05
+1

**Comment by harsaharsa** [comment] 2015-04-08 14:12
We still haven't uncovered the root cause, but we are seeing the elevated CPU usage.

It also looks like an issue with Crosswalk (i.e. the Platform WebView dosn't seem to have the same issue) and is probably related to https://github.com/AppGyver/steroids/issues/698

**Comment by neophob** [comment] 2015-04-23 12:49
see my comment @ https://github.com/AppGyver/steroids/issues/583 - i guess this is related

**Comment by badoet** [comment] 2015-04-28 15:34
platform webview from my test have the same problem as well.
i have tested it on android 5.0.1 device and android 4.4.4 device. 
on sony xperia z1
the build setup is default. i.e. all the permission checked in the build page.

just to confirm the current situation, the appgyver team currently do not experience any of this?

**Comment by badoet** [comment] 2015-04-28 15:40
![supersonic1](https://cloud.githubusercontent.com/assets/527102/7373555/c8df22f2-edff-11e4-9b00-ab64b4d11be4.jpg)
![supersonic2](https://cloud.githubusercontent.com/assets/527102/7373560/caf41e6c-edff-11e4-8047-657934a8b1b8.jpg)
the first image is when the app is active, the second image is when it is inactive.
both user and kernel cpu usage is high, esp the kernel usage.

**Comment by neophob** [comment] 2015-04-28 22:16
@badoet, jup exactly

**Comment by badoet** [comment] 2015-04-28 23:52
I build with the 4.0.5 edge android
Sorry forgot to add this info

**Comment by badoet** [comment] 2015-04-29 01:36
just tested on 3.5.3 web view ver for android. the cpu is load is fine. but the native top nav bar not displaying

**Comment by neophob** [comment] 2015-05-08 08:29
do you have any eta for this bug fix or any concrete ideas where we might give you support? this bug is really a blocker and affects all android releases.

**Comment by harsaharsa** [comment] 2015-05-08 13:12
This is at the top of the backlog – we'll tell you the instant we know more. Sorry for having left this dangling for so long, we do realize the severity of it.

**Comment by neophob** [comment] 2015-05-08 13:47
great to hear, thanks @harsaharsa

**Comment by neophob** [comment] 2015-05-19 18:11
@harsaharsa any update about this issue, did it leave the backlog?

**Comment by harsaharsa** [comment] 2015-05-20 10:07
We're closing in on a fix; there was a poller thread that was constantly running and we're figuring out the best way for an alternate implementation. Will be available soon!

**Comment by leica-apps** [comment] 2015-05-26 04:16
Bump! How's that fix going @harsaharsa ? Sorry, we're desperate!

**Comment by harsaharsa** [comment] 2015-05-26 07:26
It's fixed in our develop branch, if things don't explode I'm putting out an edge release today with the fix included!

**Comment by harsaharsa** [comment] 2015-05-26 15:28
Fix now available from build service with 4.0.6-edge1!

**Closed** 2015-06-23 09:45 UTC
Labels: Android, bug, Supersonic
