### ISSUE TITLE
ngTouch doesn't work with Supersonic

### ISSUE THREAD

**Issue by Rajan** [AppGyver/steroids#818] opened 2015-02-13 12:12 UTC
Made a simple App but it simply doesn't work.

**Comment by pre** [comment] 2015-02-13 14:22
Please provide us with some details and ask a question [in the forums](https://forums.appgyver.com). There are folks who could help you.

I'll close this issue since this doesn't provide any details how to reproduce the problem.

**Closed by pre** 2015-02-13 14:22 UTC
