### ISSUE TITLE
Loading screen not being displayed from Android drawer

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#637] opened 2014-11-24 02:32 UTC
When calling the drawers.hide method to replace the center view from the drawer the loading screen is not being displayed as it happens with iOS.

**Comment by fidoboy** [comment] 2015-02-09 16:37
Ok, now is not holidays. There is any hope? ETA? Please... :pray:

**Comment by adamgoose** [comment] 2015-03-11 17:11
Referencing #830

**Comment by harsaharsa** [comment] 2015-03-17 11:48
Closing this as duplicate of https://github.com/AppGyver/steroids/issues/644 (still no progress, sorry!)

**Closed by harsaharsa** 2015-03-17 11:48 UTC
Labels: Android, bug
