### ISSUE TITLE
Ugly repaint effect when opening/closing the 'on screen keyboard'

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#958] opened 2015-06-01 12:45 UTC
In android, when the virtual keyboard is being displayed the window shows an ugly repaint/resize behavior that it's very annoying.

**Comment by satusuuronen** [comment] 2015-06-01 14:33
Is this more prominent on certain devices or OS versions? You are right that there is some flickering. We'll see if something can be done.

**Comment by fidoboy** [comment] 2015-06-01 14:34
It's more noticeable on old devices. I'm testing using android 4.4.2 and Galaxy Note II

**Comment by fidoboy** [comment] 2015-06-01 14:35
The problem is because the DOM is being repainted and all CSS rules being applied again

**Comment by harsaharsa** [comment] 2015-06-02 13:20
@fidoboy so you're using Crosswalk, right?

**Comment by fidoboy** [comment] 2015-06-02 15:11
Yes, of course

**Comment by sunny061** [comment] 2015-07-14 05:57
I am also facing this issue with crosswalk on android devices

**Comment by harsaharsa** [comment] 2015-07-14 14:46
Closing this as a duplicate of https://github.com/AppGyver/steroids/issues/574 – which, as you can see from the discussion, is a surprisingly deep-rooted issue with Crosswalk; not much we can do. :/

**Closed by harsaharsa** 2015-07-14 14:46 UTC
Labels: investigating
