### ISSUE TITLE
Disable keyboardshrinkview on iOS

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#631] opened 2014-11-20 04:19 UTC
with current keyboard plugin the param in XML file has no effect and keyboardshrinkview is always active. It could be very useful (and nice) to have an option to disable this ugly effect.

**Comment by harsaharsa** [comment] 2015-03-19 12:47
Closed as duplicate of https://github.com/AppGyver/steroids/issues/840

**Closed by harsaharsa** 2015-03-19 12:47 UTC
Labels: bug, iOS, soon enough
