### ISSUE TITLE
<super-navbar-title> text not centred for Android when back button is present

### ISSUE THREAD

**Issue by budda** [AppGyver/steroids#903] opened 2015-04-12 19:39 UTC
The title text in the nav bar doesn't appear to be getting centered in Android when a back button appears in the left side of the super-navbar.

I'm testing with Android Lollipop on a real HTC device for what it is worth.
The functionality appears fine in iOS.

Problem noticed in my own project, and seen in the Kitchensink app too.

**Comment by poppahorse** [comment] 2015-04-21 08:14
+1, seems to happen on Jellybean also

**Comment by harsaharsa** [comment] 2015-04-23 14:31
Duplicate of https://github.com/AppGyver/steroids/issues/843 – sorry for not having tackled this yet!

**Closed by harsaharsa** 2015-04-23 14:31 UTC
