### ISSUE TITLE
Supersonic Bind sometimes is not working.

### ISSUE THREAD

**Issue by berkaey** [AppGyver/steroids#976] opened 2015-06-26 07:09 UTC
main controller like this.
```
angular.module('SteroidsApplication', [
	'supersonic'
])
.controller 'MainController', ($scope, $rootScope, supersonic) ->
	$rootScope.user = true
	$rootScope.activeUser = false
	$rootScope.activeTalkboard = false
	$rootScope.test = false

	supersonic.bind($rootScope,"user")
	supersonic.bind($rootScope,"activeUser")
	supersonic.bind($rootScope,"activeTalkboard")
	supersonic.bind($rootScope,"test")
```
and the other controller is this.
```
angular.module('SteroidsApplication')
.controller 'UserInfoController', ($scope, $rootScope, supersonic) ->
	$scope.navbarTitle = "User Info"

	closeButton = new supersonic.ui.NavigationBarButton
		title: 'close'
		onTap: () ->
			$rootScope.hideUserInfo()
		styleId: "nav-close"

	supersonic.ui.navigationBar.update
		title: $scope.navbarTitle
		overrideBackButton: false
		buttons:
			left: [closeButton]

	.then supersonic.ui.navigationBar.show()

```
and this is user-info.html
```
<body ng-app="SteroidsApplication" ng-controller="MainController">

<div ng-controller="UserInfoController">

  <div class="title">
  {{navbarTitle}}
  <br>
  {{activeUser}}
  <br>
  {{user}}
  <br>
  <div class="talkboardOpen" ng-click="showTalkboard(3)">Talkboard 3</div>
  </div>

</div>
```
some how it is not reliable. when I try to open user-info sometimes data is in sync and sometimes is not.
what am I doing wrong here? or is it just a bug.

thanks.

**Comment by berkaey** [comment] 2015-06-26 07:10
btw I tried this both on iOS simulator and iPhone 6.

**Comment by berkaey** [comment] 2015-06-26 07:11
and on addition, it is looks in sync in preloaded views somehow. this happens if I push the user-info view or open this as modal view.

**Comment by berkaey** [comment] 2015-06-26 07:14
https://share.appgyver.com/?id=67296&hash=2a257f18ea1f81e64c1fb8ee1a82964fc95e82c8679438149c43c02ef4d899d5

**Comment by berkaey** [comment] 2015-06-26 07:25
and one more thing maybe related or not when try to open first(in all views). it always works.

**Comment by berkaey** [comment] 2015-06-26 09:10
```
    $rootScope.user = true
    $rootScope.activeUser = false
    $rootScope.activeTalkboard = false
    $rootScope.test = false

    supersonic.bind($rootScope,"user")
    supersonic.bind($rootScope,"activeUser")
    supersonic.bind($rootScope,"activeTalkboard")
    supersonic.bind($rootScope,"test")
```
I notice something here.
let say I change one of the bound variable like 
```
	$rootScope.login = () ->
		$scope.user = true
```
all other bound variables turns to null. I guess this is a bug.

**Comment by berkaey** [comment] 2015-06-26 09:13
let say buttons function is
```
 $scope.user = true
```
and if I tried to click the button twice
bind won't get trigger some how so other view shows that as "false". and then every bind will be broke.

hope these will help.

**Comment by satusuuronen** [comment] 2015-06-29 07:31
Supersonic.bind does not actual synchronization of state so it only works between preloaded views.

**Comment by sunny061** [comment] 2015-07-07 02:36
@satusuuronen I am also confused as to when they should be used. Can you please give us an example where we should and shouldn't use the supersonic.bind. And what alternatives do we have for  syncing data between two views with two different controlllers, two views with the same controller (different instance I am guessing) aside from using local storage and publishing a message. I am more interested in syncing the $scope between two views using the same controller.

**Comment by harsaharsa** [comment] 2015-07-14 14:13
If you have two preloaded/started WebViews, then supersonic.bind should work fine. However, if you are pushing a completely new WebView, then you would want to fetch the new value from e.g. localstorage or pass it as a parameter with the layers.push call.

**Comment by sunny061** [comment] 2015-07-15 04:43
@harsaharsa Thanks for the info.

**Comment by harsaharsa** [comment] 2015-07-15 08:36
My understanding is that `supersonic.bind` is working as intended, so I'm closing this. Please create a repro project if some issue persists and I'll reopen this. Thanks!

**Closed by harsaharsa** 2015-07-15 08:36 UTC
