### ISSUE TITLE
steroids.logger.log doesn't work now

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/steroids#760] opened 2015-01-12 18:36 UTC
With latest releases this function stopped working. steroids.logger.log does nothing; no output into the console... (tested on iOS)

**Comment by lubasch** [comment] 2015-02-04 18:18
Same here. Interestingly it seems that once you wrap the call inside a timeout of (in my case 500ms), it works like expected.... Or  use steroids.logger.log instead but it doesnt shop up in js console in return (neither has different log levels).

**Comment by pre** [comment] 2015-02-06 12:20
Does restarting Steroids CLI and / or Scanner help?

**Comment by lubasch** [comment] 2015-02-06 12:59
Not for me.

**Comment by fidoboy** [comment] 2015-02-06 13:28
No

**Comment by pre** [comment] 2015-02-11 09:25
This issue was dicussed in the forums. The problem there was that logs are no longer delivered to the Terminal. Since Steroids 2.0 logs are available in the connect screen (in your web browser where the QR code is displayed). 

Please open a new ticket with steps to reproduce if this wasn't the problem for you. I'll close this issue because this "solution" worked for the creator of this issue in the forums.

**Closed by pre** 2015-02-11 09:25 UTC

**Comment by pre** [comment] 2015-02-11 09:32
The other issue is #765
