### ISSUE TITLE
On some devices, application starts eating 20% CPU on the background

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#583] opened 2014-10-28 05:58 UTC
If you encounter this issue, please report your device here. 

Also report the runtime name and version:
- Scanner (from Google Play)
- Scanner
- Scanner with Chromium
- Standalone
- Standalone with Chromium

And if you are using custom plugins, please provide the urls for them.

**Comment by cryoutsolutions** [comment] 2015-03-28 10:49
Hi,

I also want to report a case:
I have tested this issue on 3 phones and on all I have the same issue.

First I believed that the issue is from my app but with the default hello world app it acts the same way. The issue being that the cpu is over 20% both with app running and in the background.

I tried with google play version of scanner and also with a custom build. The same issue. The standalone version has the same issue.

Devices:
HTC M7 Android 5.0.2
MI 3 Android 4.4
Samsung S4 4.4.2

Steroids is v4.0.13

Maybe is something from how my computer builds the app? I have OSX 10.10.1

Thanks

**Comment by EdwinRikkers** [comment] 2015-04-07 14:39
+1

**Comment by neophob** [comment] 2015-04-23 12:39
My App used more than 20%CPU while idle'ling (mostly kernel time, not user space time) using the latest Build Version (v4.0.5X).

I did some tests, here are the results:
- Build using v3.5.1 without Plugin works
- Build using v3.5.1 with Plugin works
- Build using v3.5.2 with Plugin works
- Build using v3.5.3 with Plugin works
- Build using v3.5.3 (Crosswalk ARM) with Plugin works
- Build using v3.5.4 with Plugin doe NOT work

Using HTC One m8 (Android v4.4.4).

-> The Error was introduced with the Build Version 3.5.4 and is still here.

**Comment by harsaharsa** [comment] 2015-04-23 15:08
When you say "works" in the above listing, you mean "doesn't drain battery"? Thanks for the report, we'll look closer at the changes!

**Comment by neophob** [comment] 2015-04-23 15:28
correct, work means no 20% cpu usage (kernel time). btw, the cpu is at20% no matter if the application is active or not.

**Comment by neophob** [comment] 2015-04-27 06:52
any news about this issue?

**Comment by harsaharsa** [comment] 2015-04-27 11:45
Haven't had time to look into it yet – knowing the build version doesn't unfortunately help us much to narrow it down, since there were [quite a few changes introduced in 3.5.4](https://github.com/AppGyver/scanner/blob/master/changelog-android-fresh.md#354-2014-10-23-splash-screen-initial-view-and-native-css-styling). We'll keep this thread updated as we learn more.

**Comment by PeanutButterCo** [comment] 2015-04-28 23:16
+1

**Comment by harsaharsa** [comment] 2015-05-26 15:27
Fix is now available in 4.0.6-edge1. Closing this as duplicate of #841.

**Closed by harsaharsa** 2015-05-26 15:27 UTC
Labels: Android, bug
