### ISSUE TITLE
Consistent Android Crash report

### ISSUE THREAD

**Issue by mtomic** [AppGyver/steroids#860] opened 2015-03-10 05:29 UTC
I'm getting the following info from the Android Crash Report pretty regularly across different devices.  While it means nothing to me I thought it may be useful to you guys.

```
Build fingerprint: 'htc/optus_au/m7:4.4.3/KTU84L/366813.12:user/release-keys'
Revision: '3'
pid: 10102, tid: 10154, name: Chrome_InProcRe >>> my App id here <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
r0 00000000 r1 000027aa r2 00000006 r3 00000000
r4 00000006 r5 0000000c r6 000027aa r7 0000010c
r8 7d13e5c8 r9 4013d38c sl 00000000 fp 7d0403d8
ip 7d13e5a0 sp 7d13e090 lr 400ffcb9 pc 4010ecb0 cpsr 08010010
d0 723a4c415441465b d1 5f656372756f7365
d2 6863746170736964 d3 35352863632e7265
d4 0000000000000000 d5 0000000000000000
d6 0000000000000000 d7 3e8000003f3d37a7
d8 0000000000000000 d9 0000000000000000
d10 0000000000000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 6b63656843205d29 d17 3a64656c69616620
d18 656e6f706d6f632f d19 75676e612f73746e
d20 61636f6c2d72616c d21 6761726f74732d6c
d22 612f747369642f65 d23 6c2d72616c75676e
d24 3f38189a3ef46843 d25 3ff0000000000000
d26 bc6e816b02b78e96 d27 bfcffffffffffff6
d28 bf9b8041c32b2ee0 d29 3fa88bf3a22c031f
d30 3e69f10686670f4a d31 3f1150e612f17a91
scr 2a000013

backtrace:
#00 pc 00022cb0 /system/lib/libc.so (tgkill+12)
#01 pc 00013cb5 /system/lib/libc.so (pthread_kill+48)
#02 pc 00013ec9 /system/lib/libc.so (raise+10)
#03 pc 00012a63 /system/lib/libc.so
#04 pc 00022564 /system/lib/libc.so (abort+4)
#05 pc 001f8311 /data/app-lib/my-app-id/libxwalkcore.so

code around pc:
4010ec90 e8bd00f0 e3700a01 912fff1e e2600000 
4010eca0 ea00725f e92d50f0 e3a07f43 ef000000 
4010ecb0 e8bd50f0 e3700a01 912fff1e e2600000 
4010ecc0 ea007257 e92d50f0 e3a070ee ef000000 
4010ecd0 e8bd50f0 e3700a01 912fff1e e2600000 
4010ece0 ea00724f f200429a bf0080b9 f040f891 
4010ecf0 4001e92d f2c02a04 2a1080a5 8093f2c0 
4010ed00 f2c02a20 2a408088 ea4fdb7f f1bc1c92 
4010ed10 dd6c0f0a 0600e92d 0f40f1bc f500dd4a 
4010ed20 f5016e80 ebae7920 ea4f0e09 ea4f5e4e 
4010ed30 f50e5e5e ebbc7e20 dd3b1f9e f04fbfc4 
4010ed40 ebd9090a dd35199e 0a0eeb01 0a3ff02a 
4010ed50 1c9eebac bfd245e1 0c09ebac f04f46e1 
4010ed60 f8910c00 f891f240 f921f280 f921028d 
4010ed70 f8da428d f1b93000 f9000901 f900028d 
4010ed80 f10a428d d1ee0a40 0f00f1bc f5bcd02b 

code around lr:
400ffc98 447b4b13 42b3e010 6a1ed10e 44784811 
400ffca8 eee2f7fa ea34f00d 46224631 eff6f00e 
400ffcb8 d00a3001 e00b2400 2b00681b 480ad1eb 
400ffcc8 44782403 eed0f7fa f001e002 6804fa23 
400ffcd8 fa20f001 46206005 bf00bd70 0003d716 
400ffce8 0003d70a 0003d702 0003d6de bf7ef7ff 
400ffcf8 4a3e4b3d e92d447b b08b43f0 4606589c 
400ffd08 6823460d 930946a1 fa04f001 8000f8d0 
400ffd18 d0482d00 f0104628 280ff9ab d8444604 
400ffd28 ffe4f7ff d1064286 4629200f e8fef00d 
400ffd38 d03c2800 482ee02e f7fa4478 482dee14 
400ffd48 e0154478 d11342b0 482b6a06 f7fa4478 
400ffd58 4a2aee8c 46332120 a801447a fa24f013 
400ffd68 a8012101 fd3ef01a 46061c42 e011d104 
400ffd78 28006800 e02cd1e6 46294630 f00d4622 
400ffd88 1c43e93a d11e4607 f9c4f001 29046801 
```
Device/OS info
```
Last reported
Today, 11:57 AM
Reports this week
1
Reports total
1
Application version
 
1.6.0
1
Android version
 
Android 4.4
1
Device
 
HTC One (m7)
1
```

**Comment by pre** [comment] 2015-03-10 09:00
This is a duplicate of #698. Follow up there.

**Closed by pre** 2015-03-10 09:00 UTC
