### ISSUE TITLE
Unloading a WebView from drawer fails on Android

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#780] opened 2015-01-23 08:25 UTC
https://forums.appgyver.com/#!/appgyver/steroids#crash-in-android-404-e-na::unread

> all I do is have all my views in the inti block of the config so they are all started automatically and then i just do layers.push() over and over as i navigate around. I never explictly ‘start’ a view – i only do a find(id) and then push it.

**Comment by pre** [comment] 2015-01-23 08:26
On https://github.com/AppGyver/steroids/issues/656 @fidoboy reported:
> well, my procedure is to call unload method from drawer, after the center view has been replaced; i use a timer to call the unload method. This is woking fine on iOS, but doesn't work on android; the webView is not being unloaded.

**Comment by fidoboy** [comment] 2015-01-28 12:01
Crossing fingers to have this solved soon... :+1: :smile:

**Comment by fidoboy** [comment] 2015-02-04 12:58
Steps to repro this bug:
- Call steroids.drawers.hide({center: myNewView, fullChange: true}); with a non preloaded webView (as on iOS)
- Call oldView.unload() from drawer to unload the old webView

Expected result: oldView is unloaded from memory
Actual result: oldView is not unloaded

This also fails without steroids.drawers.hide method. There is no way to unload a webView from drawer on Android platform.

**Comment by fidoboy** [comment] 2015-02-04 18:04
I've also commented it here: https://github.com/AppGyver/steroids/issues/656

**Comment by EdwinRikkers** [comment] 2015-04-21 07:04
+1

**Comment by fidoboy** [comment] 2015-04-21 20:57
+100 :smile:

**Comment by fidoboy** [comment] 2015-06-01 13:40
This still fails with latest edge for Android. Returned error from the unload function is:

```A preloaded layer with identifier http://localhost/.....html could not be found```

**Comment by satusuuronen** [comment] 2015-06-01 14:37
So what is the identifier you are passing to the unload method? In any case our Android dev is checking that this works as intended. We'll keep you posted.

**Comment by fidoboy** [comment] 2015-06-01 14:41
Yes, I'm posting this also in other thread. The problem is not with the identifier cause this same code is working fine on iOS. Problem is that drawer layer does not have access to the refreshed list of layers and it doesn't "see" the requested layer and then it fails to unload it

**Comment by pentateu** [comment] 2015-06-04 18:22
To be able to unload a web view it must not be in use.

I have the following test in our test app and it works on Android and in iOS:

DrawersController.testUnloadLayer = function() {
      return steroids.layers.replace({
        view: DrawersController.center1
      }, {
        onSuccess: function() {
          ...
          return DrawersController.center2.unload({}, {
            onSuccess: function() {
              return steroids.logger.log("SUCCESS in unloading center 2 from inside the drawer");
            },
            onFailure: function() {
              ...
            }
          });
        }
      }, {
        onFailure: function() {
          ...
        }
      });
    };

**Comment by pentateu** [comment] 2015-06-04 18:49
I understand where the confusion comes from..

The following test does not result in failure in iOS, but it does in Android. The reason is because the test is flawed as explained here: https://github.com/AppGyver/steroids/issues/656
```
var webView = new steroids.views.WebView({
    'location': 'http://localhost/views/myview/myview.html',
    'id': 'http://localhost/views/myview/myview.html'
});
webView.unload();
webView = null;
```

I'll be fixing iOS to also reject this scenario and call the failure callback.

**Comment by fidoboy** [comment] 2015-06-04 18:57
No sorry, there is no confusion. It fails on Android and it works on iOS where the webView is being removed from the stack (and I can check it using the Safari inspector). To unload a webView you should reference it and you do it by creating a webView object with the location parameter, as explained in the docs. 

As I've said, it's not a failure on iOS platform, in fact it works as expected on that platform because the webView exists and it's being unloaded...

**Comment by fidoboy** [comment] 2015-06-04 18:59
May be I'm wrong, but then... how do you reference the webView to unload it? In your example, I don't understand what `DrawersController.center1` is...

**Comment by pentateu** [comment] 2015-06-04 19:00
DrawersController.center1 and DrawersController.center2 are references to preloaded web views... that I have preloaded at the top of my controller.

**Comment by fidoboy** [comment] 2015-06-04 19:02
Ok, so that's the problem, you are using the same vars. You are using a global variable inside the drawer and not requesting to the layer stack. If I use the `steroids.getApplicationState`function it doesn't return the full webViews list, only some of them

**Comment by pentateu** [comment] 2015-06-04 19:03
No.. there is no need to use same vars.. the id of the web view is the key.. I'll update my tests to reflect that.

**Comment by fidoboy** [comment] 2015-06-04 19:04
I agree, the ID is the key... and it exists. With iOS if I try to use a ID that does not exists, it fails... but it works fine when the webView exists

**Comment by fidoboy** [comment] 2015-06-04 19:06
That's why the error 'A preloaded layer with identifier http://localhost/views/myview/myview.html could not be found' displayed on Android has no sense, because my ID exists! :smile: and iOS is able to locate it and unload it, but not Android. It doesn't 'see' my webView with that same ID

**Comment by fidoboy** [comment] 2015-06-04 19:09
The problem is that the ID is not there, and thats why the API function fails to locate the ID. The source should be located in other part of your code, previous to that. I think that the unload method is working fine, it's just that the ID is not there, but without having access to the code I'm just speculating

**Comment by fidoboy** [comment] 2015-06-04 19:10
If i execute the unload method from the webView that I want to unload it works fine, well, not really cause it fails because it's already in use, but i can see that it's able to locate it. But not from the drawer

**Comment by pentateu** [comment] 2015-06-04 19:12
@fidoboy as I mentioned, I'll check the iOS behaviour as I believe it is not following the spec. If that is the case we will decide whether we change Android to be like iOS or fix iOS.

Android is working as expected:
There are only two validation in this API:
1. Checks if a preloaded web view exists with the ID provided -> Make sure the id is correct
2. Checks if the preloaded web view is not on longer in use -> Make sure the web view is no longer in use.

**unload** can only be used with preloaded web views. Non preloaded web view are automatically removed/unloaded when removed from the stack.

If you can share a repro project that shows that the above is not working I'll be happy to investigate and fix any issues on Android.

**Comment by fidoboy** [comment] 2015-06-04 19:16
Ok, so how can I reference my webView to unload it? Can you provide an example or a link to any doc where I can read it? My webView is preloaded, it's not pushed or a modal. The issue is that if I call the unload method inside a function and there is no a global object I need to instantiate the webView is some way to be able to unload it... I'm sorry, but I don't understand how to do it then...

**Comment by fidoboy** [comment] 2015-06-04 19:21
I'm using the code as it appears here: http://docs.appgyver.com/en/edge/steroids_Steroids%20Views_Steroids.views_views.WebView.md.html

```
var googleView = new steroids.views.WebView({
  location: "http://www.google.com",
  id: "search"
});

googleView.unload({}, {
  onSuccess: function() {
    alert("View has been unloaded.");
  },
  onFailure: function() {
    alert("Failed to unload.")
  }
});
'''

In that example I assume that the id 'search' is a preloaded webView that exists; the same that in my code. And also, using getAppState, why it doesn't return all the webViews, the same than when I execute it on iOS?

**Comment by fidoboy** [comment] 2015-06-04 19:23
If I execute getAppState right before calling the unload method, the returned list is not the same on iOS than on Android; on Android the webView that I want to unload is missing

**Comment by fidoboy** [comment] 2015-06-04 19:31
And I'm sorry for my insistence, but if you 'fix' something on iOS, then my code will stop working and then It will also fail on iOS where it's working right now. If it's working in your example, it's better that you share it here so I can check the differences with mine. 

In my code I'm replacing the center view from the drawer and this works fine, but then when it's completed, the old webView, the replaced one, fails to be unloaded.

**Comment by fidoboy** [comment] 2015-06-04 19:35
I'm using `steroids.drawers.hide` if it helps. I've just checked it on my code. I'm not using the replace method since the new way to accomplish that was available using the drawers.hide method

**Comment by fidoboy** [comment] 2015-06-04 19:42
May be that this is the difference with your code, double checking it now, I see that you are using the replace method, not the drawers.hide method to replace the center view. I don't remember right now if the drawers hide has onSuccess callback to place my unload there, but I've tried using a timer to unload the old webView and also right now I'm using a message from the new webView and when it's ready, it returns back a message to the drawer to unload the old one, and it works this way on iOS.

Any way, many thanks for your support. I hope that you can locate the source of the problem, and I'll try to help with all the info :+1:

**Comment by fidoboy** [comment] 2015-06-05 11:42
The layer stack should be available globally in the app. So if I preload a webView from ANY other webView or from the drawer, then I should be able to unload it again, from the same webView where I've created it or from another one. getApplicationState should return the list of all webViews and not only the ones created from the drawer. The same happens with the unload method, it should unload the webView that is preloaded even if it was preloaded from another function in that same webView or from another one.

Anyway, I'm using the drawers.hide method to replace the center, not the replace method. As I've said, I already know that doing: 

    var webView = new steroids.views.WebView({
        'location': 'http://localhost/views/myview/myview.html',
        'id': 'http://localhost/views/myview/myview.html'
    });

I'm not loadingf, preloading or pushing a webView, I'm just creating an object to instantiate the webView and then unload it. The unload method then should use my id: 'http://localhost/views/myview/myview.html' to locate the webView. This works indeed on iOS with no problems.

**Comment by harsaharsa** [comment] 2015-06-05 12:10
If `getApplicationState` is not returning the global list of all WebViews, that would cause at least Supersonic APIs to behave inconsistently – the way the JS side checks if a view is started (==preloaded) or not is to call `getApplicationState` and see if the view's id is included in the result.

**Comment by fidoboy** [comment] 2015-06-05 12:13
Well, I'm not using Supersonic, just Steroids. This shouldn't make any difference, but who knows...

**Comment by harsaharsa** [comment] 2015-06-05 12:54
So @fidoboy just to ensure, when you're calling the unload, there is a preloaded WebView (that you can access with Chrome Inspector) with that id that's not in any layer stack? If there is no preloaded WebView with the id, then it should fail with "Could not find WebView with id..." error. `unload` isn't `ensureUnloaded` – it should fail if there's nothing to unload.

Just to clarify, why is your id `http://localhost/views/myview/myview.html` and not like `myView`? Or are you accessing the initial root view?

I get the feeling that we're somehow missing the point by pasting just code snippets and examples around. Our "this is how it should work" solution is available in the Steroids.js testApp next branch: https://github.com/AppGyver/steroids-js/tree/next/testApp (go to the drawer tests)

If our code doesn't capture some case that's failing for you, please post as-simple-as-possible repro project and we'll take a look. Thanks!

**Comment by fidoboy** [comment] 2015-06-13 19:14
I'm accessing the initial root view (but also, in other tests, other webViews that I preload after the root). The testApp example you provided is a bit hard to read for me because it's using coffee script. When I use the drawer.hide method to replace the center webView it works and the new webView is loaded and it replaces the center view but THEN when I call the unload method to unload the old webView (the one that I've replaced) it fails. It remains loaded in memory. The app continues working and then when I use drawers.hide again to replace the center webView (that now it's the one loaded using drawers.hide in previous step) I can't unload again the old webView. So all the webViews are being retained in memory and I can't unload them until the app crashes

**Comment by fidoboy** [comment] 2015-06-13 19:17
With that exact same code running on iOS the webView is being unloaded and it disappears from Safari inspector; it's being unloaded with no problem using the same code, same identifier, etc. all is the same; but this fails on Android.

**Comment by fidoboy** [comment] 2015-06-13 19:22
My code to replace the center webView:

    centerView = new steroids.views.WebView({
		location: 'views/testview/testview.html'
    });
    steroids.drawers.hide({
	    center: centerView,
	    fullChange: true
    });

**Comment by fidoboy** [comment] 2015-06-26 17:37
Any updates on this issue?

**Comment by fidoboy** [comment] 2015-07-28 11:42
Ok, I believe that FINALLY I've understand how `steroids.drawers.hide` works. It seems that when replacing the center view if the view is not a preloaded one it's being preloaded automatically and then it's placed in place of the current center view. When the `steroids.drawers.hide` methodis being called again the old view is being unloaded automatically (and i was calling my own unload method for this causing problems on Android, but not on iOS due to a bug -I guess-) BUT if you want to replace the center view with the root (or initial or whatever it's called) then I should pass the ID to avoid another instance being created and duplicated. 

The issue is very hard to understand and there is no a complete documentation or examples to learn this and current docs that i've found are very confusing and contradictory. That's why I've been dealing with this issue and sending again and again reports here and there around this same problem.

Some time ago, using the chrome inspector seemed that Android was not unloading the center webViews when they was replaced from the drawer and cause I was unloading them manually in my code (and it worked fine on iOS that way) this leads me to think that something was wrong with the Android implementation. May be that @pentateu explanations are ok but I don't understand it fully, perhaps due to my bad english or to my limited knowledge about the inner of the Steroids framework. 

It could be very very useful if the Steroids documentation is reviewed and compared agains the Supersonic docs. I believe that there are many inconsistencies that need to be cleared. Some users will use only Supersonic, but there others, like me that will use Steroids only and then these kind of things needs to be explained and helped using examples to play with.

In any case, my apologies for the inconveniences and headaches caused by this issue. Thanks a lot for your patience and understanding.

**Comment by fidoboy** [comment] 2015-07-28 15:59
Taking into account my previous discovering, now I can say that there is a bug in Android platform because in this platform this doesn't works this way. When I call `steroids.getApplicationState` prior to calling the `steroids.drawers.hide` method to replace the center view, the root view, the one that it's loaded first in my app does not appears to be listed so when I try to locate it using the ID (and this works on iOS) it fails and the center view is not being replaced. By using `steroids.getApplicationState` on iOS it results in that initial webView listed, but it's not present on Android. So there is an evident inconsistence between the two platforms. If iOS is working well, then Android it's not (or vice versa). As it's working on iOS it's fine for me, but I can't understand why the preloaded webView is not listed on Android and why I can't reference to it to replace the center view. Can anyone @harsaharsa or @pentateu confirm this point and verify if there is a bug on Android or if my considerations are wrong?

Many thanks in advance

**Comment by fidoboy** [comment] 2015-07-28 16:04
I've also noticed that with Android the old webView being replaced from the drawer using `steroids.drawers.hide` method is not being unloaded as on iOS so there is more and more duplicated webViews being loaded into the stack. Using iOS, every time that I use `steroids.drawers.hide` the previous webView is being unloaded fine, releasing resources from memory.

**Comment by fidoboy** [comment] 2015-07-28 16:07
NOTE: I'm not preloading any webView cause it seems that on iOS, the webView is being preloaded automatically when I use it on `steroids.drawers.hide` method. I'm very confused and I'm not sure if I should preload them or not, mainly because on IOS, as I've pointed, it seems to work fine as it is. It's on Android platform where I can't find any way to get it working :cry:

**Comment by fidoboy** [comment] 2015-07-28 16:17
This is the current code that I'm using and which works fine on iOS:

```
    if (name == 'initialView')
        centerView = new steroids.views.WebView({
            id: 'http://localhost/views/initialview/initialview.html',
            location: 'http://localhost/views/initialview/initialview.html'
        });
    else 
        centerView = new steroids.views.WebView({
            location: newViewPath
        });
    steroids.drawers.hide({
        center: centerView,
        fullChange: true
    });
```

Where `newViewPath` has a value of this type "'http://localhost/views/oneview/oneview.html". This code works fine on iOS and it fails on Android because if `name` is "initialView" nothing happens and the center view is not being replaced and if it's any other value, then it's loaded fine but the previous center remains in memory, it's not being unloaded and also new instances of the same webView are being created again and again every time I call this piece of code from drawer.

**Comment by fidoboy** [comment] 2015-07-28 18:06
Ok, after investigating it further I'm now trying with this code:

```
     centerView.preload({}, {
				onSuccess: function() {
					steroids.drawers.hide({
						center: centerView,
						fullChange: true
					});
				}
			});
```

and doing this way it works both on iOS and Android BUT there is a big problem: on iOS this approach is worst that without preloading, because the center view is being replaced without the loading.html displayed which makes the transition smoother and more user friendly (on iOS only; on Android I haven't found any way to display the loading.html while the center view is being replaced and this is ugly). Using the preloading approach the user can notice how the screen is being painted and filled with items. Also, using the preload method then I must manually unload the previous webView to release memory.

Can't understand why it works very fine on iOS without preloading and it doesn't work on Android where more and more webViews are being stacked into memory without releasing and unloading every time as with iOS. As it's working on iOS using my previous code, without preloading is VERY COOL and useful!!!

**Comment by harsaharsa** [comment] 2015-08-17 10:40
Again, I have to stress that this is at a point where the code snippets don't help us solve the problem, but we really need a barebones repro project so we can see everything – all the code, config files etc – and verify something is not working as intended.

**Comment by fidoboy** [comment] 2015-08-17 11:32
Wow!! You can't see it with all my explanations?

**Comment by fidoboy** [comment] 2015-08-17 11:42
I'll try to create a repro and I'll upload anywhere

**Comment by fidoboy** [comment] 2015-08-28 09:08
Ok, you can download my repro here: http://www.mediafire.com/download/9tbws62kb72o468/test_app.zip try it both on iOS and Android. You'll see that it works as expected on iOS but not on Android where webViews are not being unloaded

**Comment by fidoboy** [comment] 2015-09-10 12:58
@harsaharsa I've already submitted my repro 13 days ago. I'm still waiting for an answer to this bug

**Comment by quqii** [comment] 2015-09-17 21:36
any news?

**Comment by fidoboy** [comment] 2015-09-17 22:52
Good question :smile:

**Comment by harsaharsa** [comment] 2015-10-12 11:58
Finally managed to repro this; it actually has to do only with the behavior of `steroids.drawers.hide()` when using the `center` param, not with unloading. That's why we were so confused with this, alongside with repro project that had a lot of extra fluff. See https://github.com/AppGyver/steroids/issues/1054 for the minimum repro case and follow that for updates; I've now given this to the Android team to find a place in the backlog. Closing this issue since there's a lot of unrelated buzz (I can reopen if #1054 is the wrong diagnosis).

**Closed by harsaharsa** 2015-10-12 11:58 UTC
Labels: Android, bug

**Comment by fidoboy** [comment] 2015-10-12 12:06
It has to do with unloading cause the webViews are not being unloaded on Android. When using same code on iOS, the webViews are being unloaded from the stack. You can notice it easily with my repro using chrome://inspect on Android and Safari Web inspector on iOS. There is no extra fluff, I just wanted to be sure that the submitted repro was very close to my code. Because there is no documentation about this, I was not sure about if drawer hide manages the webView unloading or not, that's why I was trying to solve it from my code by unloading the webViews after the drawer replaces the center view.
