### ISSUE TITLE
Build Service rejects valid certificate with "Detected incorrect certificate"

### ISSUE THREAD

**Issue by Sampax** [AppGyver/steroids#332] opened 2014-05-22 10:47 UTC
Intermittently the Build Service will reject a (seemingly) valid Distribution or Development certificate with the error (distribution example):

```
Detected incorrect certificate, should be a distribution certificate! Cert was:      0 valid identities found
```

Workaround: Recreating (or sometimes just reuploading) the certificate can fix the issue.

forum example: http://forums.appgyver.com/#!/steroids-build-service#urgent-build-service-dist
Pending further details.

**Comment by flexiqube** [comment] 2015-02-04 11:10
I get this error to :(

**Comment by bFlood** [comment] 2015-02-16 17:44
+1

**Comment by pre** [comment] 2015-02-17 12:40
The error message "0 valid identities found" can occur when a new provisioning profile has NOT been uploaded after creating a new certificate. The certificate and provisioning profile are linked together, so new certificates always require a new provisioning profile.

@bFlood Could you confirm if this was the issue for you? 

This issue is already fairly old and I haven't personally ever encountered this as an intermittent failure. When I have received this, the problem has always been an invalid provisioning profile. 

My best guess is that this issue is actually a configuration issue. It would be very nice to get a confirmation from @flexiqube and @bFlood if regenerating the provisioning profile fixed this problem.

**Comment by pre** [comment] 2015-02-17 12:40
The error message must be improved, though. It is misleading.

**Comment by pre** [comment] 2015-02-17 15:38
@bFlood confirmed on forums that regenerating the provisioning profile fixed the issue. 

I will close this issue as it's not a bug in the Build Service and the error message has now been improved (fix will be live tomorrow). .

**Closed by pre** 2015-02-17 15:38 UTC
Labels: bug, Build Service

**Comment by pre** [comment] 2015-02-17 15:45
Sorry, I understood wrong @bFlood's message on the forums. I'll reopen this ticket if the issue persists. We are monitoring this issue on the Build Service. 

:)

**Comment by bFlood** [comment] 2015-02-19 15:43
sorry, I think this was a bad cert on our end. we started from the beginning and now its working. please close

**Comment by an-rohangovekar** [comment] 2016-02-15 09:30
It suddenly stopped working today for me, it was working fine till last night. Now I am getting the same error for all builds. Reuploaded all the certs still getting the error

**Comment by xune3** [comment] 2016-02-15 10:12
same here, seems like there is a problem with the Apple Intermediate Certificate on the build service itself. the certificate's expiration date is the 14th of february 2016.. so yesterday.. the new certificate is valid until february 2023.. so can anyone with access to the build service update those intermediate certificates on the system?

**Comment by harsaharsa** [comment] 2016-02-15 11:08
We're working right now on fixing this, sorry for the inconvenience!

**Comment by harsaharsa** [comment] 2016-02-15 14:23
This should now be fixed, let us know if any problems persist.
