### ISSUE TITLE
I can't install steroids

### ISSUE THREAD

**Issue by cage1618** [AppGyver/steroids#799] opened 2015-01-31 16:16 UTC
/Volumes/HHD/wtc/titanium $ _ npm install steroids -g                                                                                        15-02-01 0:10:03
Password:
/
> steroids@4.0.8 preinstall /usr/lib/node_modules/steroids
> node ./bin/preinstall

sh: node: command not found

npm ERR! steroids@4.0.8 preinstall: `node ./bin/preinstall`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the steroids@4.0.8 preinstall script.
npm ERR! This is most likely a problem with the steroids package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/preinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls steroids
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/bin/node_modules/npm/bin/npm-cli.js" "install" "steroids" "-g"
npm ERR! cwd /Volumes/HHD/wtc/titanium
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

How can I resolve this promble, thanks!

**Comment by pre** [comment] 2015-02-02 08:56
You get this error because you don't have Node.js properly set up.

Please follow the "show me how" steps under the Installation Wizard to get Node.js installed. 

My personal recommendation is to use [NVM](https://github.com/creationix/nvm). 

If you have further questions, please ask them in the [Forums](https://forums.appgyver.com). This is not a bug, so I'll close this issue.

**Closed by pre** 2015-02-02 08:56 UTC
