### ISSUE TITLE
SVG Tab bar icons not shown in Fresh Android build versions

### ISSUE THREAD

**Issue by sjvdm** [AppGyver/steroids#632] opened 2014-11-20 08:46 UTC
SVG tabbar icons defined in native-styles css files show in scanner, but not on the build.

Repro: https://github.com/sjvdm/steroids-repro-svg

Tested on Android 4.0.1 stable.

SVG icon in the tabbar shows correctly as defined in android.css.

tab-bar #Tab {
  background-image: url(icons/add.svg);
}

When building using same version, no tabbar icons are shown. Platform Webview build is included in the repro under "Builds".

**Comment by s-matic** [comment] 2015-01-12 14:46
Is this issue solved yet?

**Comment by fidoboy** [comment] 2015-01-12 15:56
no, it's no solved yet. I reported it first about one or two months ago. If you use PNG images for navigation bar, then it doesn't work for retina or non retina displays (if you want to target both Android and iOS platforms with your app); if you use SVG images then it works fine on iOS but it doesn't work on Android. On Android, it works however, on scanner builds... (a bit off topic here, but this same behavior happens with other resource files on android, when using absolute path to give paths to custom cordova plugins; it works fine on scanner, but it doesn't work on ad-hoc builds)

**Comment by s-matic** [comment] 2015-01-12 16:01
That's a shame, one would think that this issue would be prioritized seeing as the tab bar really is a core feature of any app. I have the same problem in my android builds, works perfectly in the scanner and in iOS.

**Comment by fidoboy** [comment] 2015-01-12 16:02
You are right s-matic, it's a core feature... I can't understand why after two months, this issue is not solved...

**Comment by iampeter** [comment] 2015-01-18 20:19
any chances of this being solved soon?

**Comment by s-matic** [comment] 2015-01-18 21:56
I've given up on Steroids and Supersonic by now. The Appgyver team have made an amazing product but failed to support their own product. I've since moved over to Ionic which is progressing much more rapidly with major updates almost every week. Just last week they added crosswalk support and a "scanner" app.

**Comment by fidoboy** [comment] 2015-01-19 13:22
But ionic doesn't support MPA... It's the main limitation for all other frameworks

**Comment by sjvdm** [comment] 2015-01-20 07:30
Have some patience...

Just use PNG's in the meantime and define the sizes manually. Example:

tab-bar #ContribTab {
  background-image: url(icons/add.png);
 background-size:626 708; 
}

**Comment by fidoboy** [comment] 2015-01-20 13:56
Does this works on iOS and android? Does this works for navigationBar title and icons?

**Comment by sjvdm** [comment] 2015-01-20 16:10
I use this method for iOS and Android and it works.

Thus far, Nav bar is limited in iOS with native styles (from my experience anyway). I use the following for the nav bar in android.css:

navigation-bar {
  background-color: #ffffff;
}

**Comment by fidoboy** [comment] 2015-01-20 18:14
Ok, may be it works for tab bar, but can't get the navigation bar working on android with native stylesheets. There is no way to use a title image (with dimensions), SVG format doesn't work for icons on android (adhoc build), if using PNG on android, there is no way to specify image dimensions, so it don't work on retina/non retina displays.

**Comment by fidoboy** [comment] 2015-01-20 18:26
In my modest opinion this is a top priority issue, as @s-matic pointed, is a core feature; it's still unsolved after two months and yes, now i could use the wonderful Supersonic, that doesn't add anything really important and still there are big issues stopping me from finishing my app; may be this is not the right place to discuss about this, but just to enumerate some of them:

- Can't get the navigation bar working on Android (button icons and image title)
- Can't unload webViews on Android
- Push notifications doesn't work on Android
- InAppBrowser doesn't work fine on Android (it closes itself as soon as i made a background request to my server while inAppBriwser is displayed on screen)
- Loading center view from drawer in android does not display the loading screen and as a consequence the transition is not smooth, you can see the screen painting and it's very ugly.

There are other issues, but these are the more important so far... there are new releases, like supersonic, but main bugs solving is very very slow and it takes many weeks to have a simple bug solved... this is very frustrating.

**Comment by pre** [comment] 2015-01-21 12:11
@fidoboy I understand your frustration. It's pretty hectic to use a product made by a startup, let alone work in one. 

This issue is included in the near-term backlog for Android. We're right now experimenting with Crosswalk 10 with new crash fixes, getting those out would be a huge improvement for all Android apps.

For the other issues, just claiming "doesn't work" is not very helpful. As we have discussed with you in the problem reports regarding the issues you pasted above, we have not been able to reproduce all of the bugs you have reported.

* Navigation bar, which issue you are referring to?
* Unload: we haven't been able to reproduce your issue after the fix (https://github.com/AppGyver/steroids/issues/656)
* Push notifications: we haven't been able to reproduce your issue (https://github.com/AppGyver/PushNotifications/issues/7)
* InAppBrowser .. I'll update the plugin for the next edge, hopefully that'll help (https://github.com/AppGyver/steroids/issues/657)
* Loading screen with drawer: this is unfortunately not implemented https://github.com/AppGyver/steroids/issues/637

**Comment by fidoboy** [comment] 2015-01-21 12:25
I've tried my best to explain that issues. 

- Navigation bar problems on android are related to icons and image title. If i use PNG as image on Android, double size images (myicon@2x.png) doesn't work on non retina displays with android. If i use SVG (for me, it could be the easiest and more convenient method) then it doesn't work with ad-hoc build as discussed here. For image title, i can't simply specify the image size and its very big on android. Yes, i know that i could use a workaround, detecting retina from javascript and then having two different images for my icons and title, but sincerely i think that this is not a desirable method and it's a waste of resources and it adds complexity to the app code.

- For the unload problem, it's working fine for modal views now (with latests edge builds) but doesn't work for non modal views being loaded/replaced from drawer. I use the drawer hide method to replace the center view (the same code works fine on iOS) and then, after this i try to unload the old web view, but it doesn't work on android (it does it on iOS)

- Push notifications does not work for me on Android. I use initial view to receive the events and same code is working fine on iOS. My code is very straight forward, it's the same provided into the plugin read file.

- For the inAppBrowser it will be really great if finally is updated on next edge; it has many limitations and even it's working on iOS it does have some problems on iOS. Also, as I've mentioned before, doesn't work on android if the app makes a request (or any network activity) on background right before or after the plugin is being called to display the browser.

- Loading screen from drawer is a must. I think that this should be fixed ASP cause without this, the drawer method to replace center view is almost useless... it's very unpleasant and ugly to see how the center view is being painted. This same method works flawlessly from iOS.

**Comment by fidoboy** [comment] 2015-01-21 12:42
The steroids testapp is not enough to check and test methods and calls in steroids, cause real life apps are MPA (steroids doesn't has sense if it's a SPA) and you should test each method in many different conditions: from a background view, from the current active view, chaining it with other methods, with many other webViews loaded simultaneously on memory, using angular promises, etc etc. I try to help reporting here the problems i found, but it's up to you also to locate and detect the source of the problem. I want to help, i think that i'm one of the most active users on steroids community on github and also on steroids forum, and as soon as i detect a new problem or bug i report it, so your team could have some idea about what and where the engine is failing, but creating a repro is not very easy many times and more if you are not sure about the real source of the problem. As a guide i always test my code on iOS and Android, if it works in one of this two platforms and it does not work on the other then I have a clue that something is wrong with Steroids. Even doing this way, some times may be it's my fault or bad code on my side, of course, but then, if i see that also other users are reporting and confirming the same issue,  I'm almost 100% sure that there is a bug (like in this case with SVG images on navigation and tab bar)

**Comment by fidoboy** [comment] 2015-01-21 12:54
That said, my only complaint about steroids is that the development is going very very slow. Other than this, i think, as i've mentioned in other threads, that it's really amazing and revolutionary bringing the powers of native apps into the HTML5 and javascript world, I fucking love steroids :)

**Comment by pre** [comment] 2015-01-22 09:30
I understand your frustration. If we could sit down and I could explain our internal roadmap openly, then you would understand. However, at this point, things just keep burning and the development seems to be going very very slow.

Thank you for the feedback! Cheers :)

**Comment by unknownexception** [comment] 2015-01-22 11:26
@pre, sounds promising!
I'm pretty sure that AppGyver team has plans to refresh the Android support with Material UI or similar someday. Honestly, even when this issue and other related would be fixed, Android part of Supersonic still will be a third-class citizen with non-native experience (partially because Ionic now has only iOS support). Tabs isn't great for Android styleguide, etc. I finally got published Steroids app at AppStore, and I so happy about that :heart: , but trying to get things done with Android is really pain.  
To clarify, I hope there is no pressure to AppGyver Team, most of us still use this great framework for free.

**Comment by fidoboy** [comment] 2015-02-12 18:55
Any progress or ETA with this bug? I just need to use SVG images on my navigation/tab bar, and also it happens the same trying to use image as title on navigation bar. The issue is have SVG files working on adhoc builds and also allow native styles to set the image size (for images as title also)

**Comment by designed-in-india** [comment] 2015-02-25 04:15
I guess the bug is still open. Tried both edge 5 and edge 6 and the issue in Android is evident?

**Comment by fidoboy** [comment] 2015-02-25 10:30
Still open :(

**Comment by gabrielmancini** [comment] 2015-03-05 07:12
same issue here!

**Comment by fidoboy** [comment] 2015-03-10 17:10
I bet that the key to this problem is here: https://github.com/Pixate/pixate-freestyle-android/blob/6a5c1cfff3481b468a2208cc077ee81ad560a7cc/pixate-freestyle/src/com/pixate/freestyle/cg/paints/PXImagePaint.java around line 113 to load the SVG file it doesn't use a context and it uses `loadFromStream` that has no access to the folder where SVG are located (it's almost the same problem reported here: https://github.com/AppGyver/steroids/issues/805) May be that I'm wrong but this seems to be the source of this problem. If I'm right, the solution is to use a fork of the Pixate project and replace that function to use a context or android local assets... what do you think @pre ?

**Comment by fidoboy** [comment] 2015-03-10 17:23
Another bug with Android version, not directly related with this but related with native styling and navigation bar and/or tab bar is that loading external images doesn't work on Android. It works fine on iOS however. You can use `background-image: url(http://www.myserver.com/myicon.jpg)` with your button class inside your CSS file and this will work on iOS, but not on Android.

**Comment by harsaharsa** [comment] 2015-03-17 11:32
@fidoboy thanks for the detective work – that's precisely the case. This is bumped up on the backlog.

**Comment by pentateu** [comment] 2015-05-14 10:29
Good news ... the issue has been fixed and will be soon available for build (alongside other fixes).

@fidoboy I could not reproduce the issue with URL resources -> background-image: url(http://www.myserver.com/myicon.jpg)  .. 
I had a look at it while I was fixing the SVG issue and I have used png and svg remove urls and both worked fine.

#firstTab image {
    background-image: url(http://www.apple.com/apple-touch-icon.png);
}

#secondtTab image {
    background-image: url(icons/home.svg);
}

#thirdTab image {
    background-image: url(http://rationalwiki.org/w/images/3/35/Information_icon.svg);
}

**Comment by fidoboy** [comment] 2015-05-14 14:35
Amazing!! There is no words to describe what I'm feeling now after all this months waiting for this bug to be solved.

Does the CSS native styles works also with background resizing using SVG images?? It could be possible to use a SVG image as navbar title??

**Comment by fidoboy** [comment] 2015-05-14 14:45
Have you tried remote images with navbar icons? In your example I see that you are using tabbar icons to test... May be the bug is only with the navbar icons

**Comment by harsaharsa** [comment] 2015-05-19 10:20
The fix will apply to navbar SVG images too. What do you mean with "works also with background resizing"?

**Comment by fidoboy** [comment] 2015-05-19 13:26
I wanted to mean with CSS styling. Right now I can't resize properly the background-image using the background-size property. I tested it some time ago, but I remember some problems to resize the SVG image... If I'm not wrong it doesn't get resized and it looks blurred or crisp instead

**Comment by fidoboy** [comment] 2015-05-19 13:27
I am talking about CSS native styling to setup the navigation bar image icons

**Comment by pentateu** [comment] 2015-05-19 13:34
I have tested remote images with svg and other format and it works fine. It works for navbar and for any other component that support images.

**Comment by fidoboy** [comment] 2015-05-19 16:29
Ok, I've not had time already to check it, but I'll do it very soon. Having SVG images and native CSS styling working on android is really useful. Now I've only a major issue pending on android related to center view replacing from drawer and unloading views from drawer also. It's cool to have all appgyver crew working on this platform again 😊

**Comment by mantignolo** [comment] 2015-05-20 15:09
I'm trying to get the tab bar with icons for the android build (edge, version 4.0.5, Ad Hoc: Crosswalk, ARM and x86) and for me there's no way to get them showing. I just get to see tabs with small font text and the empty space where the icons should be. Tried to use .svg and .png and none worked for me... 
My code is as follows:
Structure related code:
tabs: [
    
    {
      title: "Patients"
      id: "patients"
      location: "patient#index" 
    }  
{
      title: "Profile"
      id: "profile"
      location: "main#profile" 
    }  
(other tabs)
]

CSS:
tab-bar-item#patients {
  background-image: url(icons/tab-patients-off.png);  
}

tab-bar-item#patients:selected {
  background-image: url(icons/tab-patients-on.png);  
}

tab-bar-item#profile {
  background-image: url(icons/profile.svg);
}
Am I doing something wrong?
I'm testing in 3 different devices with different versions of android : 4.1.2 to 5.x.x

**Comment by drivenrajat** [comment] 2015-05-23 13:22
I am also facing the same issue reported by @mantignolo 
Help please?

**Comment by harsaharsa** [comment] 2015-05-25 14:51
Fix for SVG icons not displaying ad hoc builds is coming in 4.0.6-edge1 later this week. PNG icons should work fine, but are they not?

**Comment by mantignolo** [comment] 2015-05-25 14:55
Nope, I'm testing now different sizes to check if that is the problem, but
till now with same proportion as the svg files they get deformed (like very
fat horizontally instead of square as they are). Which should be the right
size for using png?
If you tell me svg will work this week I'll use them in android too then!!
This are great news!! Is it granted? :D



*María Antignolo*

ADN Comunicació SL
Indústria 127, 3a planta
08025 Barcelona
Tel.: 93 450 72 41

2015-05-25 16:51 GMT+02:00 Harri Sarsa <notifications@github.com>:

**Comment by mantignolo** [comment] 2015-05-25 15:16
Ok... If I dont specify the background size or I just specify one value the
png icons get crazy, specifying two I've tried with 58px and 128px icons
and they both get very pixelated.



*María Antignolo*

ADN Comunicació SL
Indústria 127, 3a planta
08025 Barcelona
Tel.: 93 450 72 41

2015-05-25 16:55 GMT+02:00 María ADNIT <mantignolo@adncomunicacio.com>:

**Comment by lemondesigns** [comment] 2015-06-03 07:41
I don't get it, I have tried to set an icon/image for a nav-bar button but its just not working the image just does not show at all....

View:
<super-navbar>
  <super-navbar-title>
	Blah
  </super-navbar-title>
  <super-navbar-button side="left" id="search-button" onclick="alert('search')" class="search-button">&nbsp;</super-navbar-button>
</super-navbar>
...

CSS:
(app/common/native-styles/android.css)
...
navigation-bar search-button  image {

	background-image: url(icons/search.svg);
	background-size: 18;

}
...

I have also tried calling the class different things, like ".search-button" and removing "image" etc, nothing works.

**Comment by Sampax** [comment] 2015-06-10 08:22
@mantignolo have you tried SVG icons with the latest Scanner? They should now function as expected.

@lemondesigns you are describing a different [issue](https://github.com/AppGyver/steroids/issues/756), check out the thread for a workaround.

**Comment by mantignolo** [comment] 2015-06-19 06:57
Tried, SVG for tab icons are working fine for me since Harry Sarsa says (I tried the very next Monday after his message). I surrendered previously with the nav bar button icon issues in the current app, so cant say about svg images at the navigation bar.

**Closed** 2015-06-23 09:45 UTC
Labels: Android, bug
