### ISSUE TITLE
iOS native popover (iPad) causes modal webview to crash

### ISSUE THREAD

**Issue by rabbitfufu** [AppGyver/steroids#601] opened 2014-11-04 16:40 UTC
If I open a native iOS popover from within a modal webview, the modal will crash when I close the popover.

This can happen in multiple situations.  For example:

1) Select text in an input, click the "Define" button, then close the popover.
2) Call navigator.camera.getPicture with sourceType SAVEDPHOTOALBUM.

In both cases, when the popover is closed, the modal will crash.  Note if I open the popover from a webview in the layer stack, everything works fine - so this problem only affects modals.

Here is a sandbox that demonstrates the problem:  https://sandbox.appgyver.com/sandboxes/747

**Comment by roberto-robles** [comment] 2015-01-13 23:27
It seems to be related, but is the same with select inputs, multiple taps over a select input is crashing the app.

**Comment by Leeds-eBooks** [comment] 2015-01-16 15:03
:+1: I can confirm that `select` inputs cause a crash. It's a bit weird though - I have 4 select inputs on the same view - if you tap them all in quick succession, the app crashes. If you go slower, let each popover close before opening the next one, don't tax it too much, everything is fine. This is on an iPad mini retina.

**Comment by mmelkko** [comment] 2015-02-02 11:53
Fixed in 4.0.3.

**Closed by mmelkko** 2015-02-02 11:53 UTC
Labels: bug, iOS
