### ISSUE TITLE
3D acceleration is lost after using the application for some time

### ISSUE THREAD

**Issue by pre** [AppGyver/steroids#751] opened 2015-01-09 09:44 UTC
From forums https://forums.appgyver.com/#!/steroids-bugs:3d-acceleration-is-lost-aft

Repro in http://sandbox.appgyver.com/sandboxes/1094

Affects: both Adhoc and Scanner, at least 4.0.3-edge2

> Travis Brunn
I can also confirm that the problem exists in ad-hoc builds.
So, after quite a bit of testing, I have created a sandbox that demonstrates the issue (ios scanner 4.0.3-edge2):
http://sandbox.appgyver.com/sandboxes/1094
I have also narrowed down the problem. The leak appears to caused by creating custom steroids animation objects.
You'll see starting on line 54 of index.html of the sandbox, I create an animation object each time a webview is pushed to the layer stack.
~~~
var animation = new steroids.Animation({
transition: “slideFromBottom”,
duration: 0.3
});
~~~
After 50x, css transitions are bogged right down, and the only way to fix it is to force quit scanner and relaunch.
However, if I move the code that creates the animation object outside of the loop, or if I do not specify a custom animation and just use the default animation that comes with steroids.layers.push, everything works fine.

**Comment by bFlood** [comment] 2015-02-25 02:08
was this ever fixed? I just started seeing this in iOS 4.0.4edge1 custom scanner. I'm not sure its the css transitions themselves, I can just navigate around the app a lot and then go back to the page with the simple css transitions and they just stop working (everything else works fine)

**Comment by harsaharsa** [comment] 2015-03-17 12:14
It's still open – so in your use case, you never use custom animations, but just regular page transitions, and the CSS transitions slow down? Or stop working altogether?

**Comment by bFlood** [comment] 2015-03-17 12:30
I'm using a MPA, so the main page transitions are native appgyver ones. the native custom animations (which I use also) continue to work for me.

the ones that stop working are small css animations, like the flip of icon or fade/fade out of divs. no slowdown, they just stop working entirely. This can happen almost immediately in the app but sometimes it takes several page transitions for it to occur

**Comment by rabbitfufu** [comment] 2015-04-22 22:07
+1

**Comment by rabbitfufu** [comment] 2015-06-25 21:01
To clarify:

You do not need to create custom steroids animation objects repeatedly to cause this problem.

Creating a custom animation object once, and then using it repeatedly when pushing and popping to and from the layer stack is enough to cause the problem.

This seems like a pretty good reason not to use steroids custom animations at present time.  Any updates on this one?

**Comment by harsaharsa** [comment] 2015-07-14 12:58
We're working on a better single-page transition API right now (i.e. so you can properly use native animations to mask DOM content being changed); I'll make a note to investigate this issue too.

**Comment by harsaharsa** [comment] 2015-08-05 10:18
We could not reproduce this any more on an iPhone 6, see the test scenario at https://github.com/AppGyver/steroids-js/blob/next/testApp/app/views/layers/preloadedCommandCenter.html (basically, when that view is preloaded via the "test preloaded command center" button under the layers test page, it starts pushing and popping views, each time with a new animation).

Closing this until we have a working standalone repro case.

**Closed by harsaharsa** 2015-08-05 10:18 UTC
Labels: bug, iOS
