### ISSUE TITLE
Programmatic Inter-view Navigation not very efficient

### ISSUE THREAD

**Issue by obihill** [AppGyver/steroids#887] opened 2015-03-27 08:11 UTC
I am having issues with inter-view navigation. I can't seem to get things working smoothly.

When I use the `<super-navigate location="main#page-1"></super-navigate>` to navigate to a preloaded page (Page 1), it displays a spinner and then it loads the view. The whole thing takes about 2 seconds and it just seems like a long time as I would like to get the user to the view as quickly as possible.

In addition, on Page 1, there is a button that super-navigates to Page 2, where I have another button linked to a controller to execute some code. When I click this button on Page 2, I have some code that navigates back to Page 1. Here is the code I use:

```
var view_obj = new supersonic.ui.View("main#index");
supersonic.ui.layers.push(view_obj);
```

The problem is that doing this creates duplicate pages for no apparent reason, instead of simply going back to the original view. I now have 3 instances of Page 1 and 2. I have no idea why this is happening. Here's a screenshot: 

![image](https://cloud.githubusercontent.com/assets/959541/6864359/9cdf91c4-d436-11e4-952c-510c0c6e2d75.png)

I'd appreciate some clarity on this and how to fix this. And also how to get rid of the spinner which doesn't make much sense especially when the page is preloaded. 

Here is my structure.coffee file

```
module.exports =

  rootView:
    id: "index"
    location: "main#index"

  preloads: [
    {
      id: "page-1"
      location: "main#page-1"
    }
    {
      id: "page-2"
      location: "main#page-2"
    }
  ]

  tabs: []
```

Note: My platform is Android, and I'm testing using the AppGyver Scanner with Chrome DevTools for Debugging.

**Comment by chla** [comment] 2015-03-29 04:23
same issue

**Comment by harsaharsa** [comment] 2015-03-30 14:27
To access the preloaded view, you have to use
```
<super-navigate view-id="page-1">
```
instead. The "duplicate" you're seeing is caused by using `location="main#page-1"`, which causes a new WebView to be created instead of using the preloaded one. So in your screenshot, you have both your newly-created, non-preloaded WebView and the preloaded WebView running at the same time.

To get back to the root view, you shouldn't push a new view to the layer stack – your code creates another instance of the main view. Instead, you can e.g. call `supersonic.layers.popAll()` to pop the entire layer stack and return to the bottom view.

**Comment by Sampax** [comment] 2015-06-08 13:01
Closing as problem should be solved with harsarsa's advice.

**Closed by Sampax** 2015-06-08 13:01 UTC
