### ISSUE TITLE
Android 5.1 flicker

### ISSUE THREAD

**Issue by laicosly** [AppGyver/steroids#943] opened 2015-05-18 21:39 UTC
We're seeing views flicker when interacting with text inputs on Android 5.1.  I'm guessing it's related to the onscreen keyboard.  There is no flicker on iOS.

**Comment by harsaharsa** [comment] 2015-05-19 09:37
Does this happen on any other Android OS's or devices? Are you using Crosswalk or platform WebView (Google Play scanner is Crosswalk)?

**Comment by rahul4819** [comment] 2015-06-02 04:44
We are building a hybrid application (jQM and Cordova) and I am facing the same issue of keyboard flickering with number inputs as above, on Nexus 5(Android OS 5.1.1 with Webview version: 42.0.2311.138).
I have tested the same application on Nexus 5(Android OS 5.1.1 with Webview version: 39.0). and it works perfectly without any flicker.
Please let me know if you found fix for this issue.

**Comment by roberto-robles** [comment] 2015-07-02 23:32
+1 Same thing here.

**Comment by harsaharsa** [comment] 2015-07-14 13:22
This seems like a duplicate of https://github.com/AppGyver/steroids/issues/574 ? If that's the case, then it's a deep-rooted XWalk issue that's apparently quite unsolvable (we've talked with Intel directly and there seems no solution in sight, you can see the XWalk JIRA ticket in the issue linked). I'll reopen this if it's a different issue, but from above, it seems like it's only happening on crosswalk builds?

**Closed by harsaharsa** 2015-07-14 13:22 UTC
Labels: Android, investigating

**Comment by laicosly** [comment] 2015-07-20 21:34
This occurs on both Web Platform & Crosswalk.
