### ISSUE TITLE
Supersonic setAllowedRotations returns rejected promise

### ISSUE THREAD

**Issue by NomNomCameron** [AppGyver/steroids#974] opened 2015-06-24 07:12 UTC
When calling supersonic.ui.screen.setAllowedRotations the following is returned in a reject:

`API method: setAllowedOrientation not found. `

**Comment by harsaharsa** [comment] 2015-07-14 09:46
Closing as duplicate of https://github.com/AppGyver/steroids/issues/866

**Closed by harsaharsa** 2015-07-14 09:46 UTC
