### ISSUE TITLE
Serve: loads old version of angular.js in browser

### ISSUE THREAD

**Issue by aparamonov** [AppGyver/steroids#700] opened 2014-12-17 14:53 UTC
Please take a look at the following discussion: https://muut.com/appgyver#!/appgyver/steroids%23serve-loads-old-version-of
Please make attention that this issue is blocking!

**Comment by fealaer** [comment] 2015-01-05 08:08
+1

**Comment by pre** [comment] 2015-02-02 09:33
This is a duplicate of https://github.com/AppGyver/steroids/issues/746 which has been fixed.

**Closed by pre** 2015-02-02 09:33 UTC
